FROM registry.suse.com/bci/golang:1.21

ARG DAPPER_HOST_ARCH
ENV ARCH $DAPPER_HOST_ARCH

RUN zypper up -y && \
    zypper in -y -f git docker curl wget ca-certificates && \
    zypper clean

RUN if [ "${ARCH}" == "amd64" ]; then \
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.55.2; \
    fi

ENV DAPPER_ENV REPO TAG DRONE_TAG
ENV DAPPER_SOURCE /go/src/github.com/cnrancher/k8s-net-attach-def-controller
ENV DAPPER_OUTPUT ./bin ./dist
ENV DAPPER_RUN_ARGS "--privileged"
ENV DAPPER_DOCKER_SOCKET true
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
